Script started on Sunday 01 September 2013 03:17:52 PM IST
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -i -E '^[a-z0-9]+@[a-z0-9]+\.(com|org|ac\.in|edu)' 1.txt
[01;31m[Kcse@iiit.ac.in[m[K
[01;31m[Kxyz@gmail.com[m[K
[01;31m[KXYZ@GMAIL.COM[m[K
[01;31m[Kgr8@stanford.edu[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -w -E '([0-9]{1,3}.){3}[0-9]{1,3}$' 2.txt
[01;31m[K10.2.40.95[m[K
[01;31m[K0.0.0.0[m[K
[01;31m[K127.127.127.1[m[K
[01;31m[K10.10.10.10[m[K
[01;31m[K1.1.1.1[m[K
[01;31m[K256.256.256.256[m[K
[01;31m[K10.2.3.4[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -E '([0-9]{1,3})(\.\1){3}' 2.txt
[01;31m[K0.0.0.0[m[K
[01;31m[K10.10.10.10[m[K
[01;31m[K1.1.1.1[m[K
[01;31m[K256.256.256.256[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -w -E '((([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]| 25[0-5]))'
^C
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -w -E '((([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|225[0-5]))' 2.txt 
[01;31m[K10.2.40.95[m[K
[01;31m[K0.0.0.0[m[K
[01;31m[K127.127.127.1[m[K
[01;31m[K10.10.10.10[m[K
[01;31m[K1.1.1.1[m[K
[01;31m[K10.2.3.4[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -E '^(.).*\1$' 3.txt
[01;31m[Kthis is a test line for you to test[m[K
[01;31m[KAThis is a test line for you to testA[m[K
[01;31m[Kthis is a test line for you to test hhhhhhhht[m[K
[01;31m[Kaaaaaaaaaaaa[m[K
[01;31m[KAazzzzzzaA[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep  -E '^.(.).*\1.$' 3.txt
[01;31m[Kthis is a test line for you to test hhhhhhhht[m[K
[01;31m[Kaaaaaaaaaaaa[m[K
[01;31m[KAazzzzzzaA[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$  grep -i -E '^<(..)>.*</\1>$' 4.txt
[01;31m[K<h1>HEADING1</h1>[m[K
[01;31m[K<h1>HEADING1</H1>[m[K
[01;31m[K<h2>HEADING1</h2>[m[K
[01;31m[K<h6>HEADING1</h6>[m[K
[01;31m[K<h7>HEADING1</H7>[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -E '^('\''|//|#)' 5.txt
[01;31m[K//[m[KThis is a comment
[01;31m[K'[m[KThis is a comment
[01;31m[K'[m[K#This is a comment
[01;31m[K#[m[KThis is a comment
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -E -v '^('\''|//|#)' 5.txt
This is the first line
This is not a comment
/This is not a comment/
/This is also not a comment
is this a comment#
is this not a // comment
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ grep -E '^[A-Z]{2}\s[0-9]{2}\s[A-Z]{2}\s[0-9]{1,4}$' 6.txt
[01;31m[KMH 15 BH 6549[m[K
[01;31m[KMH 12 CJ 2239[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ sed 's_\(.\)\1\+_\1_g' 7.txt
abc
asdf asaca werae
asfa s dsdfs

]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ find ~ -cmin -600 -type f
/home/satya/asgn/sce/a/2/.201350508_commands.txt.swp
/home/satya/asgn/sce/a/2/practice_big.txt
/home/satya/asgn/sce/a/2/typescript
/home/satya/asgn/sce/a/2/a_9_big_big.txt
/home/satya/asgn/sce/a/2/201350508_explaination.txt
/home/satya/asgn/sce/a/2/Assignment2_big_big.tar.gz
/home/satya/asgn/sce/a/2/201350508.script
/home/satya/asgn/sce/a/2/SCEAssignment2V3_big_big.pdf
/home/satya/asgn/sce/a/2/typescript_big_big
/home/satya/asgn/sce/a/2/201350508_commands.txt
/home/satya/asgn/sce/a/2/practice_big_big.txt
/home/satya/.xsession-errors
/home/satya/.gstreamer-0.10/registry.x86_64.bin
/home/satya/.pulse/ccc333826b91d6a19d6334f60000000a-default-source
/home/satya/.pulse/ccc333826b91d6a19d6334f60000000a-device-volumes.tdb
/home/satya/.pulse/ccc333826b91d6a19d6334f60000000a-default-sink
/home/satya/.ICEauthority
/home/satya/.gnome2/keyrings/login.keyring
/home/satya/.local/share/telepathy/mission-control/accounts-goa.cfg
/home/satya/.local/share/recently-used.xbel
/home/satya/.local/share/zeitgeist/fts.index/flintlock
/home/satya/.local/share/zeitgeist/activity.sqlite-shm
/home/satya/.local/share/zeitgeist/activity.sqlite-wal
/home/satya/.local/share/gvfs-metadata/home-6733b3bb.log
/home/satya/.local/share/gvfs-metadata/root-021506eb.log
/home/satya/.local/share/gvfs-metadata/home
/home/satya/.bash_history
/home/satya/.xsession-errors.old
/home/satya/.macromedia/Flash_Player/#SharedObjects/W3TQSCBF/s.ytimg.com/soundData.sol
/home/satya/Pictures/Screenshot from 2013-09-01 14:01:10.png
/home/satya/.dmrc
/home/satya/.gconf/apps/nautilus/preferences/%gconf.xml
/home/satya/.gconf/apps/gnome-terminal/profiles/Default/%gconf.xml
/home/satya/.gconf/apps/gnome-terminal/profiles/Profile0/%gconf.xml
/home/satya/.gconf/apps/eog/ui/%gconf.xml
/home/satya/.gconf/apps/eog/view/%gconf.xml
/home/satya/.dbus/session-bus/ccc333826b91d6a19d6334f60000000a-0
/home/satya/.viminfo
/home/satya/.mozilla/firefox/4oy18fm0.default/urlclassifierkey3.txt
/home/satya/.mozilla/firefox/4oy18fm0.default/sessionstore.bak
/home/satya/.mozilla/firefox/4oy18fm0.default/healthreport.sqlite-wal
/home/satya/.mozilla/firefox/4oy18fm0.default/webappsstore.sqlite-wal
/home/satya/.mozilla/firefox/4oy18fm0.default/cookies.sqlite-shm
/home/satya/.mozilla/firefox/4oy18fm0.default/.parentlock
/home/satya/.mozilla/firefox/4oy18fm0.default/webapps/webapps.json
/home/satya/.mozilla/firefox/4oy18fm0.default/sessionstore.js
/home/satya/.mozilla/firefox/4oy18fm0.default/prefs.js
/home/satya/.mozilla/firefox/4oy18fm0.default/places.sqlite-wal
/home/satya/.mozilla/firefox/4oy18fm0.default/signons.sqlite
/home/satya/.mozilla/firefox/4oy18fm0.default/formhistory.sqlite
/home/satya/.mozilla/firefox/4oy18fm0.default/healthreport.sqlite-shm
/home/satya/.mozilla/firefox/4oy18fm0.default/places.sqlite-shm
/home/satya/.mozilla/firefox/4oy18fm0.default/cookies.sqlite
/home/satya/.mozilla/firefox/4oy18fm0.default/places.sqlite
/home/satya/.mozilla/firefox/4oy18fm0.default/permissions.sqlite
/home/satya/.mozilla/firefox/4oy18fm0.default/webappsstore.sqlite-shm
/home/satya/.mozilla/firefox/4oy18fm0.default/cookies.sqlite-wal
/home/satya/.cache/chromium/Default/Media Cache/index
/home/satya/.cache/chromium/Default/Media Cache/data_3
/home/satya/.cache/chromium/Default/Media Cache/data_0
/home/satya/.cache/chromium/Default/Media Cache/data_2
/home/satya/.cache/chromium/Default/Media Cache/data_1
/home/satya/.cache/chromium/Default/Cache/f_006e9d
/home/satya/.cache/chromium/Default/Cache/f_006eff
/home/satya/.cache/chromium/Default/Cache/f_006eec
/home/satya/.cache/chromium/Default/Cache/f_006f02
/home/satya/.cache/chromium/Default/Cache/f_006ebc
/home/satya/.cache/chromium/Default/Cache/f_006f3c
/home/satya/.cache/chromium/Default/Cache/f_006efe
/home/satya/.cache/chromium/Default/Cache/f_006f49
/home/satya/.cache/chromium/Default/Cache/f_006f48
/home/satya/.cache/chromium/Default/Cache/f_006f5e
/home/satya/.cache/chromium/Default/Cache/f_006eb3
/home/satya/.cache/chromium/Default/Cache/f_006ec6
/home/satya/.cache/chromium/Default/Cache/f_006ee7
/home/satya/.cache/chromium/Default/Cache/f_006ebd
/home/satya/.cache/chromium/Default/Cache/f_006f4f
/home/satya/.cache/chromium/Default/Cache/f_006e88
/home/satya/.cache/chromium/Default/Cache/f_006edf
/home/satya/.cache/chromium/Default/Cache/f_006edb
/home/satya/.cache/chromium/Default/Cache/f_006ef4
/home/satya/.cache/chromium/Default/Cache/f_006edc
/home/satya/.cache/chromium/Default/Cache/f_006eb1
/home/satya/.cache/chromium/Default/Cache/f_006ef9
/home/satya/.cache/chromium/Default/Cache/f_006f69
/home/satya/.cache/chromium/Default/Cache/f_006f01
/home/satya/.cache/chromium/Default/Cache/f_006f5c
/home/satya/.cache/chromium/Default/Cache/f_006eb5
/home/satya/.cache/chromium/Default/Cache/f_006f07
/home/satya/.cache/chromium/Default/Cache/f_006f13
/home/satya/.cache/chromium/Default/Cache/f_006ee3
/home/satya/.cache/chromium/Default/Cache/f_006ecb
/home/satya/.cache/chromium/Default/Cache/f_006f5a
/home/satya/.cache/chromium/Default/Cache/f_006eef
/home/satya/.cache/chromium/Default/Cache/f_006eae
/home/satya/.cache/chromium/Default/Cache/f_006f62
/home/satya/.cache/chromium/Default/Cache/f_006ee0
/home/satya/.cache/chromium/Default/Cache/f_006f3f
/home/satya/.cache/chromium/Default/Cache/f_006f3a
/home/satya/.cache/chromium/Default/Cache/f_006efb
/home/satya/.cache/chromium/Default/Cache/f_006f12
/home/satya/.cache/chromium/Default/Cache/f_006ec5
/home/satya/.cache/chromium/Default/Cache/f_006ec4
/home/satya/.cache/chromium/Default/Cache/f_006efa
/home/satya/.cache/chromium/Default/Cache/f_006f24
/home/satya/.cache/chromium/Default/Cache/f_006ecf
/home/satya/.cache/chromium/Default/Cache/f_006ec3
/home/satya/.cache/chromium/Default/Cache/f_006f16
/home/satya/.cache/chromium/Default/Cache/f_006f23
/home/satya/.cache/chromium/Default/Cache/f_006f39
/home/satya/.cache/chromium/Default/Cache/index
/home/satya/.cache/chromium/Default/Cache/f_006e9b
/home/satya/.cache/chromium/Default/Cache/f_006f3d
/home/satya/.cache/chromium/Default/Cache/f_006ea5
/home/satya/.cache/chromium/Default/Cache/f_006f21
/home/satya/.cache/chromium/Default/Cache/f_006e97
/home/satya/.cache/chromium/Default/Cache/f_006f46
/home/satya/.cache/chromium/Default/Cache/f_006f61
/home/satya/.cache/chromium/Default/Cache/f_006ec2
/home/satya/.cache/chromium/Default/Cache/f_006ed0
/home/satya/.cache/chromium/Default/Cache/f_006f5f
/home/satya/.cache/chromium/Default/Cache/f_006f6e
/home/satya/.cache/chromium/Default/Cache/f_006e8e
/home/satya/.cache/chromium/Default/Cache/data_3
/home/satya/.cache/chromium/Default/Cache/f_006efd
/home/satya/.cache/chromium/Default/Cache/f_006f4e
/home/satya/.cache/chromium/Default/Cache/f_006f66
/home/satya/.cache/chromium/Default/Cache/f_006e8b
/home/satya/.cache/chromium/Default/Cache/f_006eed
/home/satya/.cache/chromium/Default/Cache/f_006ecc
/home/satya/.cache/chromium/Default/Cache/f_006f22
/home/satya/.cache/chromium/Default/Cache/f_006ef6
/home/satya/.cache/chromium/Default/Cache/f_006f41
/home/satya/.cache/chromium/Default/Cache/f_006e92
/home/satya/.cache/chromium/Default/Cache/f_006ee6
/home/satya/.cache/chromium/Default/Cache/f_006eeb
/home/satya/.cache/chromium/Default/Cache/f_006ee1
/home/satya/.cache/chromium/Default/Cache/f_006f59
/home/satya/.cache/chromium/Default/Cache/f_006f50
/home/satya/.cache/chromium/Default/Cache/f_006f18
/home/satya/.cache/chromium/Default/Cache/f_006f76
/home/satya/.cache/chromium/Default/Cache/f_006ec9
/home/satya/.cache/chromium/Default/Cache/f_006f35
/home/satya/.cache/chromium/Default/Cache/f_006e99
/home/satya/.cache/chromium/Default/Cache/f_006ef1
/home/satya/.cache/chromium/Default/Cache/f_006eb6
/home/satya/.cache/chromium/Default/Cache/f_006f04
/home/satya/.cache/chromium/Default/Cache/f_006e8a
/home/satya/.cache/chromium/Default/Cache/f_006ece
/home/satya/.cache/chromium/Default/Cache/f_006eb8
/home/satya/.cache/chromium/Default/Cache/f_006f3e
/home/satya/.cache/chromium/Default/Cache/f_006e98
/home/satya/.cache/chromium/Default/Cache/f_006f65
/home/satya/.cache/chromium/Default/Cache/f_006f4c
/home/satya/.cache/chromium/Default/Cache/f_006f44
/home/satya/.cache/chromium/Default/Cache/f_006f45
/home/satya/.cache/chromium/Default/Cache/data_0
/home/satya/.cache/chromium/Default/Cache/f_006f6a
/home/satya/.cache/chromium/Default/Cache/f_006f36
/home/satya/.cache/chromium/Default/Cache/f_006f6b
/home/satya/.cache/chromium/Default/Cache/f_006eee
/home/satya/.cache/chromium/Default/Cache/f_006ee2
/home/satya/.cache/chromium/Default/Cache/f_006ee4
/home/satya/.cache/chromium/Default/Cache/f_006ee5
/home/satya/.cache/chromium/Default/Cache/f_006eb0
/home/satya/.cache/chromium/Default/Cache/f_006eb4
/home/satya/.cache/chromium/Default/Cache/f_006ebb
/home/satya/.cache/chromium/Default/Cache/f_006ef5
/home/satya/.cache/chromium/Default/Cache/f_006e89
/home/satya/.cache/chromium/Default/Cache/data_2
/home/satya/.cache/chromium/Default/Cache/f_006eb2
/home/satya/.cache/chromium/Default/Cache/f_006f6f
/home/satya/.cache/chromium/Default/Cache/f_006ef2
/home/satya/.cache/chromium/Default/Cache/f_006e9a
/home/satya/.cache/chromium/Default/Cache/f_006e8f
/home/satya/.cache/chromium/Default/Cache/f_006f14
/home/satya/.cache/chromium/Default/Cache/f_006ecd
/home/satya/.cache/chromium/Default/Cache/f_006ef8
/home/satya/.cache/chromium/Default/Cache/f_006eca
/home/satya/.cache/chromium/Default/Cache/f_006ef7
/home/satya/.cache/chromium/Default/Cache/f_006ef0
/home/satya/.cache/chromium/Default/Cache/f_006eaf
/home/satya/.cache/chromium/Default/Cache/f_006eb7
/home/satya/.cache/chromium/Default/Cache/f_006ed1
/home/satya/.cache/chromium/Default/Cache/f_006ec0
/home/satya/.cache/chromium/Default/Cache/f_006f06
/home/satya/.cache/chromium/Default/Cache/f_006f15
/home/satya/.cache/chromium/Default/Cache/f_006f64
/home/satya/.cache/chromium/Default/Cache/f_006eba
/home/satya/.cache/chromium/Default/Cache/f_006f00
/home/satya/.cache/chromium/Default/Cache/f_006ef3
/home/satya/.cache/chromium/Default/Cache/f_006f71
/home/satya/.cache/chromium/Default/Cache/f_006e95
/home/satya/.cache/chromium/Default/Cache/f_006e93
/home/satya/.cache/chromium/Default/Cache/f_006f43
/home/satya/.cache/chromium/Default/Cache/f_006ede
/home/satya/.cache/chromium/Default/Cache/f_006e8c
/home/satya/.cache/chromium/Default/Cache/f_006ebe
/home/satya/.cache/chromium/Default/Cache/f_006f03
/home/satya/.cache/chromium/Default/Cache/f_006f47
/home/satya/.cache/chromium/Default/Cache/f_006ebf
/home/satya/.cache/chromium/Default/Cache/f_006edd
/home/satya/.cache/chromium/Default/Cache/f_006f42
/home/satya/.cache/chromium/Default/Cache/f_006ed2
/home/satya/.cache/chromium/Default/Cache/f_006ec7
/home/satya/.cache/chromium/Default/Cache/f_006ee9
/home/satya/.cache/chromium/Default/Cache/f_006ec1
/home/satya/.cache/chromium/Default/Cache/f_006f5d
/home/satya/.cache/chromium/Default/Cache/f_006f37
/home/satya/.cache/chromium/Default/Cache/f_006eb9
/home/satya/.cache/chromium/Default/Cache/f_006f38
/home/satya/.cache/chromium/Default/Cache/f_006ee8
/home/satya/.cache/chromium/Default/Cache/f_006eea
/home/satya/.cache/chromium/Default/Cache/f_006efc
/home/satya/.cache/chromium/Default/Cache/data_1
/home/satya/.cache/chromium/Default/Cache/f_006e96
/home/satya/.cache/chromium/Default/Cache/f_006f3b
/home/satya/.cache/chromium/Default/Cache/f_006ec8
/home/satya/.cache/chromium/Default/Cache/f_006f51
/home/satya/.cache/chromium/Default/Cache/f_006e9c
/home/satya/.cache/chromium/Default/Cache/f_006f40
/home/satya/.cache/chromium/Default/Cache/f_006f63
/home/satya/.cache/chromium/Default/Cache/f_006f05
/home/satya/.cache/dconf/user
/home/satya/.cache/software-center/reviews.ubuntu.com_reviews_api_1.0_review-stats-pkgnames.p__5.1.db.dbenv/__db.001
/home/satya/.cache/software-center/reviews.ubuntu.com_reviews_api_1.0_review-stats-pkgnames.p__5.1.db.dbenv/__db.004
/home/satya/.cache/software-center/reviews.ubuntu.com_reviews_api_1.0_review-stats-pkgnames.p__5.1.db.dbenv/__db.002
/home/satya/.cache/software-center/reviews.ubuntu.com_reviews_api_1.0_review-stats-pkgnames.p__5.1.db.dbenv/__db.003
/home/satya/.cache/unity-lens-video/videos.db
/home/satya/.cache/sso/sso-client.log
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-phish-shavar.sbstore
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-malware-simple.pset
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-phish-shavar.cache
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-malware-shavar.sbstore
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-phish-simple.cache
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-malware-shavar.pset
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-malware-simple.cache
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-phish-simple.pset
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-phish-simple.sbstore
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/test-malware-simple.sbstore
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-phish-shavar.pset
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/safebrowsing/goog-malware-shavar.cache
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/_CACHE_CLEAN_
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/thumbnails/1c5543dc929a477a00ad05d1e5ebd692.png
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/thumbnails/9cd85ac82b731b7697042916a934caf0.png
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/thumbnails/3d5b7a6d49016f6ad93705a1e10f8d21.png
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/3/1D/54EC9d01
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/3/AC/25713d01
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/_CACHE_MAP_
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/8/86/C673Ed01
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/_CACHE_002_
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/_CACHE_001_
/home/satya/.cache/mozilla/firefox/4oy18fm0.default/Cache/_CACHE_003_
/home/satya/.cache/ubuntuone/log/syncdaemon-exceptions.log.2013-09-01_09-25-12
/home/satya/.cache/ubuntuone/log/syncdaemon-exceptions.log.2013-09-01_01-10-35
/home/satya/.cache/ubuntuone/log/syncdaemon.log.2013-09-01_01-10-35
/home/satya/.cache/ubuntuone/log/credentials.log
/home/satya/.cache/ubuntuone/log/syncdaemon.log.2013-09-01_13-50-21
/home/satya/.cache/ubuntuone/log/syncdaemon-exceptions.log.2013-09-01_12-50-21
/home/satya/.cache/ubuntuone/log/syncdaemon-exceptions.log
/home/satya/.cache/ubuntuone/log/syncdaemon.log
/home/satya/.cache/ubuntuone/log/syncdaemon.log.2013-09-01_09-25-12
/home/satya/.gtk-bookmarks
/home/satya/.Xauthority
/home/satya/.config/chromium/Safe Browsing Bloom Prefix Set
/home/satya/.config/chromium/Safe Browsing Bloom
/home/satya/.config/chromium/Local State
/home/satya/.config/chromium/Safe Browsing Cookies-journal
/home/satya/.config/chromium/Safe Browsing Extension Blacklist
/home/satya/.config/chromium/Safe Browsing Download
/home/satya/.config/chromium/Safe Browsing Download Whitelist
/home/satya/.config/chromium/Default/Shortcuts
/home/satya/.config/chromium/Default/Extension Cookies
/home/satya/.config/chromium/Default/Last Session
/home/satya/.config/chromium/Default/Shortcuts-journal
/home/satya/.config/chromium/Default/Sync Data/SyncData.sqlite3
/home/satya/.config/chromium/Default/Sync Data/SyncData.sqlite3-journal
/home/satya/.config/chromium/Default/Network Action Predictor-journal
/home/satya/.config/chromium/Default/Last Tabs
/home/satya/.config/chromium/Default/Web Data-journal
/home/satya/.config/chromium/Default/Favicons-journal
/home/satya/.config/chromium/Default/Current Session
/home/satya/.config/chromium/Default/Top Sites-journal
/home/satya/.config/chromium/Default/TransportSecurity
/home/satya/.config/chromium/Default/Cookies-journal
/home/satya/.config/chromium/Default/GPUCache/index
/home/satya/.config/chromium/Default/GPUCache/data_1
/home/satya/.config/chromium/Default/databases/chrome-extension_mijlebbfndhelmdpmllgcfadlkankhok_0/1
/home/satya/.config/chromium/Default/Top Sites
/home/satya/.config/chromium/Default/Extension State/MANIFEST-000243
/home/satya/.config/chromium/Default/Extension State/000245.log
/home/satya/.config/chromium/Default/Extension State/CURRENT
/home/satya/.config/chromium/Default/Extension State/LOG
/home/satya/.config/chromium/Default/Extension State/000241.sst
/home/satya/.config/chromium/Default/Extension State/000244.sst
/home/satya/.config/chromium/Default/Extension State/LOG.old
/home/satya/.config/chromium/Default/History Index 2013-08
/home/satya/.config/chromium/Default/Network Action Predictor
/home/satya/.config/chromium/Default/Visited Links
/home/satya/.config/chromium/Default/QuotaManager-journal
/home/satya/.config/chromium/Default/History Index 2013-09
/home/satya/.config/chromium/Default/Current Tabs
/home/satya/.config/chromium/Default/History Provider Cache
/home/satya/.config/chromium/Default/Login Data-journal
/home/satya/.config/chromium/Default/Bookmarks.bak
/home/satya/.config/chromium/Default/File System/Origins/CURRENT
/home/satya/.config/chromium/Default/File System/Origins/LOG
/home/satya/.config/chromium/Default/File System/Origins/LOG.old
/home/satya/.config/chromium/Default/File System/Origins/000522.log
/home/satya/.config/chromium/Default/File System/Origins/MANIFEST-000521
/home/satya/.config/chromium/Default/File System/000/p/00/00000000
/home/satya/.config/chromium/Default/File System/000/p/Paths/CURRENT
/home/satya/.config/chromium/Default/File System/000/p/Paths/LOG
/home/satya/.config/chromium/Default/File System/000/p/Paths/MANIFEST-000511
/home/satya/.config/chromium/Default/File System/000/p/Paths/LOG.old
/home/satya/.config/chromium/Default/File System/000/p/Paths/000512.log
/home/satya/.config/chromium/Default/File System/000/p/.usage
/home/satya/.config/chromium/Default/Local Extension Settings/abjcfabbhafbcdfjoecdgepllmpfceif/MANIFEST-000169
/home/satya/.config/chromium/Default/Local Extension Settings/abjcfabbhafbcdfjoecdgepllmpfceif/CURRENT
/home/satya/.config/chromium/Default/Local Extension Settings/abjcfabbhafbcdfjoecdgepllmpfceif/LOG
/home/satya/.config/chromium/Default/Local Extension Settings/abjcfabbhafbcdfjoecdgepllmpfceif/000170.log
/home/satya/.config/chromium/Default/Local Extension Settings/abjcfabbhafbcdfjoecdgepllmpfceif/LOG.old
/home/satya/.config/chromium/Default/History
/home/satya/.config/chromium/Default/Session Storage/MANIFEST-000353
/home/satya/.config/chromium/Default/Session Storage/000357.log
/home/satya/.config/chromium/Default/Session Storage/CURRENT
/home/satya/.config/chromium/Default/Session Storage/LOG
/home/satya/.config/chromium/Default/Session Storage/000359.sst
/home/satya/.config/chromium/Default/Session Storage/LOG.old
/home/satya/.config/chromium/Default/Web Data
/home/satya/.config/chromium/Default/History Index 2013-08-journal
/home/satya/.config/chromium/Default/History-journal
/home/satya/.config/chromium/Default/Preferences
/home/satya/.config/chromium/Default/Cookies
/home/satya/.config/chromium/Default/Extension Cookies-journal
/home/satya/.config/chromium/Default/Login Data
/home/satya/.config/chromium/Default/QuotaManager
/home/satya/.config/chromium/Default/Local Storage/http_disqus.com_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/https_talkgadget.google.com_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_mgijmajocgfcbeboacabfgobmjgjcoja_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/http_www.youtube.com_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/https_plus.google.com_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/https_talkgadget.google.com_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_gighmmpiobklfepjocnamgkkbiglidom_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/http_stackoverflow.com_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_mijlebbfndhelmdpmllgcfadlkankhok_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/http_www.geeksforgeeks.org_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/http_disqus.com_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_pioclpoplcdbaefihamjohnefbikjilc_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_mgijmajocgfcbeboacabfgobmjgjcoja_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_pioclpoplcdbaefihamjohnefbikjilc_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_cfhdojbkjhnklbpkdaibdccddilifddb_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/http_stackoverflow.com_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/https_plus.google.com_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/http_www.youtube.com_0.localstorage
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_gighmmpiobklfepjocnamgkkbiglidom_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_mijlebbfndhelmdpmllgcfadlkankhok_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/chrome-extension_cfhdojbkjhnklbpkdaibdccddilifddb_0.localstorage-journal
/home/satya/.config/chromium/Default/Local Storage/http_www.geeksforgeeks.org_0.localstorage-journal
/home/satya/.config/chromium/Default/Extension Rules/000208.log
/home/satya/.config/chromium/Default/Extension Rules/MANIFEST-000207
/home/satya/.config/chromium/Default/Extension Rules/CURRENT
/home/satya/.config/chromium/Default/Extension Rules/LOG
/home/satya/.config/chromium/Default/Extension Rules/LOG.old
/home/satya/.config/chromium/Default/Favicons
/home/satya/.config/chromium/Safe Browsing Cookies
/home/satya/.config/chromium/Safe Browsing Csd Whitelist
/home/satya/.config/dconf/user
/home/satya/.config/autostart/indicator-multiload.desktop
/home/satya/.config/nautilus/desktop-metadata
/home/satya/.config/eog/accels
/home/satya/.config/google-googletalkplugin/googletalkplugin_ws_port
/home/satya/.config/google-googletalkplugin/googletalkplugin_port
/home/satya/.config/google-googletalkplugin/gtbplugin.log
/home/satya/.thumbnails/normal/8b80af089aa0ab1467c5911136cccccf.png
/home/satya/.thumbnails/normal/7073796ea4d0b96a7c234fd693446ffc.png
/home/satya/.thumbnails/normal/ad717f4e6b3ee0a5274d56caeda12f1e.png
/home/satya/.thumbnails/normal/46cf0ab4b40ebd145dd23c635b55e7e0.png
/home/satya/.thumbnails/normal/aab27be3fc5a6cdfec5d7193e95192ba.png
/home/satya/.thumbnails/normal/a785e8a260794cc32bf2fe252fa60b91.png
/home/satya/.thumbnails/normal/62be7d69d0c30dc6d9118609d1c409eb.png
/home/satya/.thumbnails/normal/6345257e8a3957e9b4ad8394c1efc0bf.png
/home/satya/.thumbnails/normal/f9855a23fde8d7f69684ed98cc8d3cec.png
/home/satya/.thumbnails/normal/a7a0bd83f3bafd5b329a1ba05802561e.png
/home/satya/.thumbnails/normal/e517f80ab230dc5a1891d19eaf21c8f5.png
/home/satya/.thumbnails/normal/f73150ed152354edd048b24cfa8d37cc.png
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ sed -i -e '1,3d' 9.txt
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ awk '/an/' 10.txt
This is an apple
This is an umbrella.
This is aan egg
this is nananananana
banananananana
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ sed 's/^\/*.*\*\/$//g' 11.txt

/* this is not a */comment
/* this is not a *comment/

/* this is not a *comment/



/*THIS IS  COMMENT/*

]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$  grep -E '^[-]?([0-9]{1,}|[0-9]{1,}\.[0-9]{1,})$' 12.txt
[01;31m[K1[m[K
[01;31m[K23[m[K
[01;31m[K-4[m[K
[01;31m[K1.0[m[K
[01;31m[K0.1[m[K
[01;31m[K1.234234[m[K
[01;31m[K-1.23453[m[K
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$  ls -lS | awk '{if ($5>1048576 && $1 ~ /^-/) { print $9}};'|awk -F. '{ printf("mv %s %s_big",$0,$1); for(i=2;i<= NF;i++) {printf("%s%s",FS,$i) }{printf("\n")}}'|awk '{system($0)}'
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ ls
10.txt  201350508_commands.txt      3.txt  7.txt            [0m[01;31mAssignment2_big_big.tar.gz[0m  SCEAssignment2V3_big_big.pdf
11.txt  201350508_explaination.txt  4.txt  9.txt            employee.txt                test.txt
12.txt  201350508.script            5.txt  a_11.txt         practice_big_big.txt        typescript
1.txt   2.txt                       6.txt  a_9_big_big.txt  practice_big.txt            typescript_big_big
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC:~/asgn/sce/a/2$ awk 'BEGIN { printf("invenroty report\n") }{ print $1,$2,$3 ,$2*$3  }END{print "Done!"}' employee.txt
invenroty report
Name Rate Hours_Worked 0
A 10 4 40
B 8 3 24
C 6 11 66
D 14 7 98
E 7 14 98
F 20 0 0
   0
Done!
]0;satya@Satya-PC: ~/asgn/sce/a/2satya@Satya-PC